apiVersion: v1
kind: Service
metadata:
  name: my-service  # Đặt tên cho dịch vụ
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

